### PR TITLE
Fix for invalid packageName generation on Windows

### PR DESCRIPTION
**Pull request by wooshie**
Replaced hardcoded  separator "/" with platform dependant File.separator.

### CODE REVIEW

**Comment by simschla** [comment]
we are facing the same issue addressed in this PR and reported in #2, merging PR and releasing new version would be appreciated :)

**Comment by simschla** [comment]
@jochenseeber is there any chance you are going to integrate this fix and publish a new version of the plugin? Seems like an easy enough fix...

**Comment by jochenseeber** [comment]
Thanks for the contribution. And the patience :-) The day job... New release is 0.2.2

**Comment by simschla** [comment]
I can't find the new release on https://plugins.gradle.org/plugin/me.seeber.wsimport - is the information there outdated?

**Comment by jochenseeber** [comment]
It's currently on jcenter, plugins.gradle.org release will follow. You can add the following to your build script to use it:

``` groovy
buildscript {
    repositories {
        jcenter()
    }
}
```

**Comment by simschla** [comment]
If I use the new 0.2.2 Version from jcenter I get:

```
Execution failed for task ':project1:wsimport'.
> No signature of method: org.gradle.process.internal.DefaultExecActionFactory.newJavaExecAction() is applicable for argument types: () values: []
  Possible solutions: newExecAction()
[...]
Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.process.internal.DefaultExecActionFactory.newJavaExecAction() is applicable for argument types: () values: []
Possible solutions: newExecAction()
        at me.seeber.gradle.wsimport.WsimportTask$_execute_closure1.doCall(WsimportTask.groovy:64)
[...]
        at me.seeber.gradle.wsimport.WsimportTask.execute(WsimportTask.groovy:62)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
```

Gradle Version:  Gradle 2.11

Has something in the dependencies changed?

**Pull request merged**
